version: '3.4'
services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
  web:
    build: .
    command: >
      bash -c "bundle exec rake rabbitmq:setup
      && rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/blog
    ports:
      - "3000:3000"
    depends_on:
      - rabbitmq
    environment:
      - AMPQ_ADDRESS=amqp://rabbitmq:5672
    links:
      - rabbitmq

  sneaker_worker:
    build: ../dashboard
    environment:
      - Workers=PostsWorker
    command: bundle exec rake sneakers:run
    volumes:
      - ../dashboard:/dashboard
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
